root_path = "."

# watch_target_dirs = ["example", "targetdir"]
watch_target_dirs = ["."]
watch_exclude_dirs = [".git", "vendor", "tmp"]
watch_file_ext = [".go", ".tmpl", ".html"]

build_target_dir = "tmp"
build_target_name = "myserver"
build_command = "go"
build_options = ["build", "-v"]

start_options = ["-v"]
pid_file = "./tmp/pid"
